name: Deploy FE Page

on:
  push:
    branches: ["main"]
    paths:
      - 'fe/**'
      - '.github/workflows/fe.yml'
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.20.0
          package-manager-cache: false

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        env:
          VITE_API_BASE_URL: ${{ vars.BASE_URL }}
        run: |
          pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: fe/build/client

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
