name: Deploy FE Page

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.20.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: |
          npm install -g corepack
          corepack enable
          # 根据 package.json 强制安装特定版本的 pnpm (若有的话)
          corepack prepare pnpm@latest --activate

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: fe/pnpm-lock.yaml

      - name: Build dist
        working-directory: fe
        run: |
          pnpm install
          pnpm build

      - name: Deploy
        uses: jamesives/github-pages-deploy-action@v4.6.1
        with:
          branch: fe-gh-pages
          folder: fe/build/client
          clean: true
